// <auto-generated />
using System;
using System.Text.Json;
using ChefMenu.Domain.Enums;
using ChefMenu.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChefMenu.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250629140717_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "category_type", new[] { "ingredients", "kitchenwares" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "measurement_unit", new[] { "count", "grams", "milliliters" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "system_action_type", new[] { "create", "hard_delete", "soft_delete", "update" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_action_type", new[] { "blacklist", "dislike", "like", "save", "view" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_feedback_status", new[] { "active", "closed", "open", "resolved" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_feedback_type", new[] { "bug", "feature", "support" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "admin", "chef", "cook", "moderator", "system" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "fuzzystrmatch");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChefMenu.Domain.Features.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ImageUri")
                        .HasColumnType("text")
                        .HasColumnName("image_uri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<CategoryType>("Type")
                        .HasColumnType("category_type")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_categories_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_categories_deleted_by_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name"), new[] { "Id" });

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_categories_updated_by_id");

                    b.HasIndex(new[] { "Name" }, "ix_categories_name_fuzzy")
                        .HasDatabaseName("ix_categories_name_fuzzy");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_categories_name_fuzzy"), "gist");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_categories_name_fuzzy"), new[] { "gist_trgm_ops" });

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Categories.CategoryIngredient", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.HasKey("CategoryId", "IngredientId")
                        .HasName("pk_category_ingredient");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_category_ingredient_created_by_id");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_category_ingredient_ingredient_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("IngredientId"), new[] { "CategoryId" });

                    b.ToTable("category_ingredient", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Categories.CategoryKitchenware", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("KitchenwareId")
                        .HasColumnType("integer")
                        .HasColumnName("kitchenware_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.HasKey("CategoryId", "KitchenwareId")
                        .HasName("pk_category_kitchenware");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_category_kitchenware_created_by_id");

                    b.HasIndex("KitchenwareId")
                        .HasDatabaseName("ix_category_kitchenware_kitchenware_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("KitchenwareId"), new[] { "CategoryId" });

                    b.ToTable("category_kitchenware", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Comments.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int?>("RecipeCollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_collection_id");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.Property<int?>("UserFeedbackId")
                        .HasColumnType("integer")
                        .HasColumnName("user_feedback_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_comments_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_comments_deleted_by_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_comments_parent_id")
                        .HasFilter("parent_id IS NOT NULL");

                    b.HasIndex("RecipeCollectionId")
                        .HasDatabaseName("ix_comments_recipe_collection_id")
                        .HasFilter("recipe_collection_id IS NOT NULL");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_comments_recipe_id")
                        .HasFilter("recipe_id IS NOT NULL");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_comments_updated_by_id");

                    b.HasIndex("UserFeedbackId")
                        .HasDatabaseName("ix_comments_user_feedback_id")
                        .HasFilter("user_feedback_id IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("comments", null, t =>
                        {
                            t.HasCheckConstraint("ck_union", "   (parent_id IS NOT NULL)::int\r\n   + (user_id IS NOT NULL)::int\r\n   + (recipe_id IS NOT NULL)::int\r\n   + (recipe_collection_id IS NOT NULL)::int\r\n   + (user_feedback_id IS NOT NULL)::int\r\n   = 1");
                        });
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Ingredients.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ImageUri")
                        .HasColumnType("text")
                        .HasColumnName("image_uri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_ingredients");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_ingredients_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_ingredients_deleted_by_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ingredients_name");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name"), new[] { "Id" });

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_ingredients_updated_by_id");

                    b.HasIndex(new[] { "Name" }, "ix_ingredients_name_fuzzy")
                        .HasDatabaseName("ix_ingredients_name_fuzzy");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_ingredients_name_fuzzy"), "gist");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_ingredients_name_fuzzy"), new[] { "gist_trgm_ops" });

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Ingredients.IngredientRecipe", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<MeasurementUnit>("MeasurementUnit")
                        .HasColumnType("measurement_unit")
                        .HasColumnName("measurement_unit");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("IngredientId", "RecipeId")
                        .HasName("pk_ingredient_recipe");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_ingredient_recipe_created_by_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_ingredient_recipe_recipe_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("RecipeId"), new[] { "IngredientId" });

                    b.ToTable("ingredient_recipe", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Keywords.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_keywords");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_keywords_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_keywords_deleted_by_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_keywords_name");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name"), new[] { "Id" });

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_keywords_updated_by_id");

                    b.HasIndex(new[] { "Name" }, "ix_keywords_name_fuzzy")
                        .HasDatabaseName("ix_keywords_name_fuzzy");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_keywords_name_fuzzy"), "gist");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_keywords_name_fuzzy"), new[] { "gist_trgm_ops" });

                    b.ToTable("keywords", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Keywords.KeywordRecipe", b =>
                {
                    b.Property<int>("KeywordId")
                        .HasColumnType("integer")
                        .HasColumnName("keyword_id");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.HasKey("KeywordId", "RecipeId")
                        .HasName("pk_keyword_recipe");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_keyword_recipe_created_by_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_keyword_recipe_recipe_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("RecipeId"), new[] { "KeywordId" });

                    b.ToTable("keyword_recipe", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Keywords.KeywordRecipeCollection", b =>
                {
                    b.Property<int>("KeywordId")
                        .HasColumnType("integer")
                        .HasColumnName("keyword_id");

                    b.Property<int>("RecipeCollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_collection_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.HasKey("KeywordId", "RecipeCollectionId")
                        .HasName("pk_keyword_recipe_collection");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_keyword_recipe_collection_created_by_id");

                    b.HasIndex("RecipeCollectionId")
                        .HasDatabaseName("ix_keyword_recipe_collection_recipe_collection_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("RecipeCollectionId"), new[] { "KeywordId" });

                    b.ToTable("keyword_recipe_collection", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Kitchenwares.Kitchenware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ImageUri")
                        .HasColumnType("text")
                        .HasColumnName("image_uri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_kitchenwares");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_kitchenwares_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_kitchenwares_deleted_by_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_kitchenwares_name");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name"), new[] { "Id" });

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_kitchenwares_updated_by_id");

                    b.HasIndex(new[] { "Name" }, "ix_kitchenwares_name_fuzzy")
                        .HasDatabaseName("ix_kitchenwares_name_fuzzy");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_kitchenwares_name_fuzzy"), "gist");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_kitchenwares_name_fuzzy"), new[] { "gist_trgm_ops" });

                    b.ToTable("kitchenwares", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Kitchenwares.KitchenwareRecipe", b =>
                {
                    b.Property<int>("KitchenwareId")
                        .HasColumnType("integer")
                        .HasColumnName("kitchenware_id");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.HasKey("KitchenwareId", "RecipeId")
                        .HasName("pk_kitchenware_recipe");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_kitchenware_recipe_created_by_id");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_kitchenware_recipe_recipe_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("RecipeId"), new[] { "KitchenwareId" });

                    b.ToTable("kitchenware_recipe", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.RecipeCollections.RecipeCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ImageUri")
                        .HasColumnType("text")
                        .HasColumnName("image_uri");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_recipe_collections");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_recipe_collections_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_recipe_collections_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_recipe_collections_updated_by_id");

                    b.HasIndex("Name", "CreatedById")
                        .IsUnique()
                        .HasDatabaseName("ix_recipe_collections_name_created_by_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name", "CreatedById"), new[] { "Id" });

                    b.HasIndex(new[] { "Name" }, "ix_recipe_collections_name_fuzzy")
                        .HasDatabaseName("ix_recipe_collections_name_fuzzy");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_recipe_collections_name_fuzzy"), "gist");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_recipe_collections_name_fuzzy"), new[] { "gist_trgm_ops" });

                    b.ToTable("recipe_collections", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<JsonElement>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ImageUri")
                        .HasColumnType("text")
                        .HasColumnName("image_uri");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_recipes");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_recipes_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_recipes_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_recipes_updated_by_id");

                    b.HasIndex("Name", "CreatedById")
                        .IsUnique()
                        .HasDatabaseName("ix_recipes_name_created_by_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Name", "CreatedById"), new[] { "Id" });

                    b.HasIndex(new[] { "Name" }, "ix_recipes_name_fuzzy")
                        .HasDatabaseName("ix_recipes_name_fuzzy");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Name" }, "ix_recipes_name_fuzzy"), "gist");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Name" }, "ix_recipes_name_fuzzy"), new[] { "gist_trgm_ops" });

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Recipes.RecipeRecipeCollection", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("RecipeCollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_collection_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.HasKey("RecipeId", "RecipeCollectionId")
                        .HasName("pk_recipe_recipe_collection");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_recipe_recipe_collection_created_by_id");

                    b.HasIndex("RecipeCollectionId")
                        .HasDatabaseName("ix_recipe_recipe_collection_recipe_collection_id");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("RecipeCollectionId"), new[] { "RecipeId" });

                    b.ToTable("recipe_recipe_collection", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.SystemActionHistories.SystemActionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<JsonElement>("New")
                        .HasColumnType("jsonb")
                        .HasColumnName("new");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonElement>("Old")
                        .HasColumnType("jsonb")
                        .HasColumnName("old");

                    b.Property<SystemActionType>("Type")
                        .HasColumnType("system_action_type")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_system_action_histories");

                    b.ToTable("system_action_histories", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.SystemConfigs.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<JsonElement>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Key")
                        .HasName("pk_system_configs");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_system_configs_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_system_configs_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_system_configs_updated_by_id");

                    b.ToTable("system_configs", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.UserActions.UserAction", b =>
                {
                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<UserActionType>("Type")
                        .HasColumnType("user_action_type")
                        .HasColumnName("type");

                    b.Property<int>("ChefId")
                        .HasColumnType("integer")
                        .HasColumnName("chef_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("KitchenwareId")
                        .HasColumnType("integer")
                        .HasColumnName("kitchenware_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<int>("KeywordId")
                        .HasColumnType("integer")
                        .HasColumnName("keyword_id");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_id");

                    b.Property<int>("RecipeCollectionId")
                        .HasColumnType("integer")
                        .HasColumnName("recipe_collection_id");

                    b.Property<int>("CommentId")
                        .HasColumnType("integer")
                        .HasColumnName("comment_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("CreatedById", "Type", "ChefId", "IngredientId", "KitchenwareId", "CategoryId", "KeywordId", "RecipeId", "RecipeCollectionId", "CommentId")
                        .HasName("pk_user_actions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_user_actions_category_id")
                        .HasFilter("category_id IS NOT NULL");

                    b.HasIndex("ChefId")
                        .HasDatabaseName("ix_user_actions_chef_id")
                        .HasFilter("chef_id IS NOT NULL");

                    b.HasIndex("CommentId")
                        .HasDatabaseName("ix_user_actions_comment_id")
                        .HasFilter("comment_id IS NOT NULL");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_user_actions_ingredient_id")
                        .HasFilter("ingredient_id IS NOT NULL");

                    b.HasIndex("KeywordId")
                        .HasDatabaseName("ix_user_actions_keyword_id")
                        .HasFilter("keyword_id IS NOT NULL");

                    b.HasIndex("KitchenwareId")
                        .HasDatabaseName("ix_user_actions_kitchenware_id")
                        .HasFilter("kitchenware_id IS NOT NULL");

                    b.HasIndex("RecipeCollectionId")
                        .HasDatabaseName("ix_user_actions_recipe_collection_id")
                        .HasFilter("recipe_collection_id IS NOT NULL");

                    b.HasIndex("RecipeId")
                        .HasDatabaseName("ix_user_actions_recipe_id")
                        .HasFilter("recipe_id IS NOT NULL");

                    b.ToTable("user_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_union", "   (chef_id IS NOT NULL)::int\r\n   + (ingredient_id IS NOT NULL)::int\r\n   + (kitchenware_id IS NOT NULL)::int\r\n   + (category_id IS NOT NULL)::int\r\n   + (keyword_id IS NOT NULL)::int\r\n   + (recipe_id IS NOT NULL)::int\r\n   + (recipe_collection_id IS NOT NULL)::int\r\n   + (comment_id IS NOT NULL)::int\r\n   = 1");
                        });
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.UserFeedbacks.UserFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsignedToId")
                        .HasColumnType("integer")
                        .HasColumnName("asigned_to_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<UserFeedbackStatus>("Status")
                        .HasColumnType("user_feedback_status")
                        .HasColumnName("status");

                    b.Property<UserFeedbackType>("Type")
                        .HasColumnType("user_feedback_type")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("pk_user_feedback");

                    b.HasIndex("AsignedToId")
                        .HasDatabaseName("ix_user_feedback_asigned_to_id");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_feedback_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_user_feedback_deleted_by_id");

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_user_feedback_updated_by_id");

                    b.ToTable("user_feedback", (string)null);
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 101L, null, null, null, null, null);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ImageUri")
                        .HasColumnType("text")
                        .HasColumnName("image_uri");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_users_created_by_id");

                    b.HasIndex("DeletedById")
                        .HasDatabaseName("ix_users_deleted_by_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Email"), new[] { "Id" });

                    b.HasIndex("UpdatedById")
                        .HasDatabaseName("ix_users_updated_by_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Username"), new[] { "Id" });

                    b.HasIndex(new[] { "Username" }, "ix_users_username_fuzzy")
                        .HasDatabaseName("ix_users_username_fuzzy");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Username" }, "ix_users_username_fuzzy"), "gist");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex(new[] { "Username" }, "ix_users_username_fuzzy"), new[] { "gist_trgm_ops" });

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = 1,
                            Description = "InternalSystem",
                            DisplayName = "InternalSystem",
                            Email = "chefmenu.internal@gmail.com",
                            IsPublic = false,
                            PasswordHash = "",
                            Role = UserRole.System,
                            Username = "InternalSystem"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = 1,
                            Description = "PublicSystem",
                            DisplayName = "PublicSystem",
                            Email = "chefmenu.public@gmail.com",
                            IsPublic = false,
                            PasswordHash = "",
                            Role = UserRole.System,
                            Username = "PublicSystem"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedById = 1,
                            Description = "AiSystem",
                            DisplayName = "AiSystem",
                            Email = "chefmenu.ai@gmail.com",
                            IsPublic = false,
                            PasswordHash = "",
                            Role = UserRole.System,
                            Username = "AiSystem"
                        });
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Categories.Category", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_categories_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_users_deleted_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Categories.CategoryIngredient", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_ingredient_categories_category_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_ingredient_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Ingredients.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_ingredient_ingredients_ingredient_id");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Categories.CategoryKitchenware", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_kitchenware_categories_category_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_kitchenware_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Kitchenwares.Kitchenware", "Kitchenware")
                        .WithMany()
                        .HasForeignKey("KitchenwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_kitchenware_kitchenwares_kitchenware_id");

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("Kitchenware");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Comments.Comment", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany("CreatedComments")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_users_deleted_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Comments.Comment", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_comments_parent_id");

                    b.HasOne("ChefMenu.Domain.Features.RecipeCollections.RecipeCollection", "RecipeCollection")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeCollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_recipe_collections_recipe_collection_id");

                    b.HasOne("ChefMenu.Domain.Features.Recipes.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_recipes_recipe_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_users_updated_by_id");

                    b.HasOne("ChefMenu.Domain.Features.UserFeedbacks.UserFeedback", "UserFeedback")
                        .WithMany("Comments")
                        .HasForeignKey("UserFeedbackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_user_feedback_user_feedback_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "User")
                        .WithMany("ReceivedComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("Parent");

                    b.Navigation("Recipe");

                    b.Navigation("RecipeCollection");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");

                    b.Navigation("UserFeedback");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Ingredients.Ingredient", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingredients_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ingredients_users_deleted_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ingredients_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Ingredients.IngredientRecipe", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_recipe_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Ingredients.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_recipe_ingredients_ingredient_id");

                    b.HasOne("ChefMenu.Domain.Features.Recipes.Recipe", "Recipe")
                        .WithMany("IngredientRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingredient_recipe_recipes_recipe_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Keywords.Keyword", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keywords_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_keywords_users_deleted_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_keywords_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Keywords.KeywordRecipe", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keyword_recipe_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Keywords.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keyword_recipe_keywords_keyword_id");

                    b.HasOne("ChefMenu.Domain.Features.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keyword_recipe_recipes_recipe_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Keyword");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Keywords.KeywordRecipeCollection", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keyword_recipe_collection_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Keywords.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keyword_recipe_collection_keywords_keyword_id");

                    b.HasOne("ChefMenu.Domain.Features.RecipeCollections.RecipeCollection", "RecipeCollection")
                        .WithMany()
                        .HasForeignKey("RecipeCollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_keyword_recipe_collection_recipe_collections_recipe_collect");

                    b.Navigation("CreatedBy");

                    b.Navigation("Keyword");

                    b.Navigation("RecipeCollection");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Kitchenwares.Kitchenware", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_kitchenwares_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_kitchenwares_users_deleted_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_kitchenwares_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Kitchenwares.KitchenwareRecipe", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_kitchenware_recipe_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Kitchenwares.Kitchenware", "Kitchenware")
                        .WithMany()
                        .HasForeignKey("KitchenwareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_kitchenware_recipe_kitchenwares_kitchenware_id");

                    b.HasOne("ChefMenu.Domain.Features.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_kitchenware_recipe_recipes_recipe_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Kitchenware");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.RecipeCollections.RecipeCollection", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany("CreatedRecipeCollections")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_collections_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recipe_collections_users_deleted_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recipe_collections_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Recipes.Recipe", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany("CreatedRecipes")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recipes_users_deleted_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recipes_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Recipes.RecipeRecipeCollection", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_recipe_collection_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.RecipeCollections.RecipeCollection", "RecipeCollection")
                        .WithMany()
                        .HasForeignKey("RecipeCollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_recipe_collection_recipe_collections_recipe_collecti");

                    b.HasOne("ChefMenu.Domain.Features.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recipe_recipe_collection_recipes_recipe_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Recipe");

                    b.Navigation("RecipeCollection");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.SystemConfigs.SystemConfig", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_system_configs_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_system_configs_users_deleted_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_system_configs_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.UserActions.UserAction", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_actions_categories_category_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "Chef")
                        .WithMany()
                        .HasForeignKey("ChefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_actions_users_chef_id");

                    b.HasOne("ChefMenu.Domain.Features.Comments.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_actions_comments_comment_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_actions_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Ingredients.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_actions_ingredients_ingredient_id");

                    b.HasOne("ChefMenu.Domain.Features.Keywords.Keyword", "Keyword")
                        .WithMany()
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_actions_keywords_keyword_id");

                    b.HasOne("ChefMenu.Domain.Features.Kitchenwares.Kitchenware", "Kitchenware")
                        .WithMany()
                        .HasForeignKey("KitchenwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_actions_kitchenwares_kitchenware_id");

                    b.HasOne("ChefMenu.Domain.Features.RecipeCollections.RecipeCollection", "RecipeCollection")
                        .WithMany()
                        .HasForeignKey("RecipeCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_actions_recipe_collections_recipe_collection_id");

                    b.HasOne("ChefMenu.Domain.Features.Recipes.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_actions_recipes_recipe_id");

                    b.Navigation("Category");

                    b.Navigation("Chef");

                    b.Navigation("Comment");

                    b.Navigation("CreatedBy");

                    b.Navigation("Ingredient");

                    b.Navigation("Keyword");

                    b.Navigation("Kitchenware");

                    b.Navigation("Recipe");

                    b.Navigation("RecipeCollection");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.UserFeedbacks.UserFeedback", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "AsignedTo")
                        .WithMany()
                        .HasForeignKey("AsignedToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_feedback_users_asigned_to_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany("CreatedUserFeedback")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_feedback_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_feedback_users_deleted_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_feedback_users_updated_by_id");

                    b.Navigation("AsignedTo");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Users.User", b =>
                {
                    b.HasOne("ChefMenu.Domain.Features.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_users_created_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_deleted_by_id");

                    b.HasOne("ChefMenu.Domain.Features.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_users_updated_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Comments.Comment", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.RecipeCollections.RecipeCollection", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Recipes.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("IngredientRecipes");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.UserFeedbacks.UserFeedback", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ChefMenu.Domain.Features.Users.User", b =>
                {
                    b.Navigation("CreatedComments");

                    b.Navigation("CreatedRecipeCollections");

                    b.Navigation("CreatedRecipes");

                    b.Navigation("CreatedUserFeedback");

                    b.Navigation("ReceivedComments");
                });
#pragma warning restore 612, 618
        }
    }
}
